// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjvgB70gXpoGgtWZT0-NeSnXqDSGDnPrw',
    appId: '1:452481818330:web:fc7f362eb453378b184fe3',
    messagingSenderId: '452481818330',
    projectId: 'crow-insta-clone',
    authDomain: 'crow-insta-clone.firebaseapp.com',
    storageBucket: 'crow-insta-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0H4PstWvv3iYgYnv687F9ggJJ73dXmRU',
    appId: '1:452481818330:android:41c55727af9f0842184fe3',
    messagingSenderId: '452481818330',
    projectId: 'crow-insta-clone',
    storageBucket: 'crow-insta-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKxBoCz6JMCE9AXs3wwsoBvB2WQyFHQPA',
    appId: '1:452481818330:ios:33a329b612607c79184fe3',
    messagingSenderId: '452481818330',
    projectId: 'crow-insta-clone',
    storageBucket: 'crow-insta-clone.appspot.com',
    iosClientId: '452481818330-avo7ga2qr50h724v22ekuesploigp1dq.apps.googleusercontent.com',
    iosBundleId: 'com.instaclonecrow.crowInstaClone',
  );
}
